# DevBuddy config file
# See https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md

env:
  ENV: development

up:
  - go:
      version: 1.22.1
      modules: true
  - custom:
      name: Create local install directory
      met?: '[ "*" = "`cat .devbuddy/.gitignore`" ]'
      meet: mkdir -p .devbuddy && echo '*' > .devbuddy/.gitignore
  - custom:
      name: Install golangci-lint
      met?: test -x .devbuddy/golangci-lint && .devbuddy/golangci-lint --version | grep -q 'v1.57.1'
      meet: GOBIN=$PWD/.devbuddy go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.57.1

commands:
  test: go test -cover -race ./...
  lint: .devbuddy/golangci-lint run

open:
  devbuddy: https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md#config-devyml
