# DevBuddy config file
# See https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md

env:
  ENV: development

up:
  - go:
      version: 1.20.5
      modules: true
  - custom:
      name: Install golangci-lint
      met?: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3
      meet: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.53.3

commands:
  test: go test -cover -race ./...
  lint: golangci-lint run

open:
  devbuddy: https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md#config-devyml
