# DevBuddy config file
# See https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md

env:
  ENV: development

up:
  - go:
      version: 1.25.7
      modules: true
  - custom:
      name: Create local install directory
      met?: '[ "*" = "`cat .devbuddy/.gitignore`" ]'
      meet: mkdir -p .devbuddy && echo '*' > .devbuddy/.gitignore
  - custom:
      name: Install golangci-lint
      met?: test -x .devbuddy/golangci-lint && .devbuddy/golangci-lint --version | grep -q '2.8.0'
      meet: GOBIN=$PWD/.devbuddy go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.8.0

commands:
  test: go test -cover -race ./...
  lint: .devbuddy/golangci-lint run

open:
  devbuddy: https://github.com/devbuddy/devbuddy/blob/master/docs/Config.md#config-devyml
